---
title: "Untitled"
author: "Eguchi"
date: "2018/6/28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

## package loading
```{r setup, include=FALSE}
library(tidyverse); library(lightgbm); library(magrittr); library(moments);
library(keras); library(sessioninfo); library(IROmiss); library(xgboost); library(caret); library(irlba); library(catboost)
```

```{r}
use_backend(backend = "plaidml")
```

## prev
```{r, include=FALSE}
tr <- read_csv("application_train.csv") 
te <- read_csv("application_test.csv")
```

```{r, include=FALSE}
tri <- 1:nrow(tr)
y <- tr$TARGET

tr_te <- tr %>% 
  select(-TARGET) %>% 
  bind_rows(te) %>%
  select(-SK_ID_CURR) %>% 
  mutate_if(is.character, as.factor) %>% 
  mutate(na = apply(., 1, function(x) sum(is.na(x))),
         DAYS_EMPLOYED = ifelse(DAYS_EMPLOYED == 365243, NA, DAYS_EMPLOYED),
         DAYS_EMPLOYED_PERC = sqrt(DAYS_EMPLOYED / DAYS_BIRTH),
         INCOME_CREDIT_PERC = AMT_INCOME_TOTAL / AMT_CREDIT,
         INCOME_PER_PERSON = log1p(AMT_INCOME_TOTAL / CNT_FAM_MEMBERS),
         ANNUITY_INCOME_PERC = sqrt(AMT_ANNUITY / (1 + AMT_INCOME_TOTAL)),
         LOAN_INCOME_RATIO = AMT_CREDIT / AMT_INCOME_TOTAL,
         ANNUITY_LENGTH = AMT_CREDIT / AMT_ANNUITY,
         CHILDREN_RATIO = CNT_CHILDREN / CNT_FAM_MEMBERS, 
         CREDIT_TO_GOODS_RATIO = AMT_CREDIT / AMT_GOODS_PRICE,
         INC_PER_CHLD = AMT_INCOME_TOTAL / (1 + CNT_CHILDREN),
         SOURCES_PROD = EXT_SOURCE_1 * EXT_SOURCE_2 * EXT_SOURCE_3,
         CAR_TO_BIRTH_RATIO = OWN_CAR_AGE / DAYS_BIRTH,
         CAR_TO_EMPLOY_RATIO = OWN_CAR_AGE / DAYS_EMPLOYED,
         PHONE_TO_BIRTH_RATIO = DAYS_LAST_PHONE_CHANGE / DAYS_BIRTH,
         PHONE_TO_BIRTH_RATIO = DAYS_LAST_PHONE_CHANGE / DAYS_EMPLOYED) 

docs <- str_subset(names(tr), "FLAG_DOC")
live <- str_subset(names(tr), "(?!NFLAG_)(?!FLAG_DOC)(?!_FLAG_)FLAG_")
inc_by_org <- tr_te %>% 
  group_by(ORGANIZATION_TYPE) %>% 
  summarise(m = median(AMT_INCOME_TOTAL)) %$% 
  setNames(as.list(m), ORGANIZATION_TYPE)

rm(tr, te, fn, sum_bureau, sum_cc_balance, 
   sum_payments, sum_pc_balance, sum_prev); gc()
```


```{r, include=FALSE}
set.seed(71)
dtest <- as.data.frame(tr_te[-tri, ], stringsAsFactors = TRUE)
work <- as.data.frame(tr_te[tri, ], stringsAsFactors = TRUE)
```

```{r}
set.seed(71)
tri <- caret::createDataPartition(y, p = 0.8, list = F) %>% c()
dtrain <-  catboost.load_pool(work[tri, ], label = y[tri])
dval <-  catboost.load_pool(work[-tri, ], label = y[-tri])
```

```{r}
fit_params <- list(iterations = 900,
                   thread_count = 7,
                   eval_metric = 'AUC',
                   loss_function = 'Logloss:Border=0.5',
                   border_count = 64,
                   depth = 7,
                   learning_rate = 0.05,
                   l2_leaf_reg = 0.5,
                   od_type = 'Iter',
                   od_wait = 30,
                   random_seed = 71,
                   bootstrap_type= 'Bernoulli',
                   class_weights = c(0.2, 1)
                   )
```

```{r}
model <- catboost.train(dtrain, dval, fit_params)
```

```{r}
test <-  catboost.load_pool(dtest)
```

```{r, include=FALSE}
read_csv("sample_submission.csv") %>%  
  mutate(SK_ID_CURR = as.integer(SK_ID_CURR),
         TARGET = catboost.predict(model, test, prediction_type = 'Probability')) %>%
  write_csv("cat_first.csv")
```





