---
title: "Untitled"
author: "Eguchi"
date: "2018/6/28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

## package loading
```{r setup, include=FALSE}
library(tidyverse); library(lightgbm); library(magrittr); library(moments); library(missRanger); library(zoo); library(factoextra)
library(keras); library(sessioninfo); library(IROmiss); library(xgboost); library(caret); library(irlba); 
library(catboost); library(data.table); library(stringr); library(fastknn)
```

```{r}
use_backend(backend = "plaidml")
```

## prev
```{r, include=FALSE}
tr <- read_csv("application_train.csv") 
te <- read_csv("application_test.csv")
```

```{r, include=FALSE}
tri <- 1:nrow(tr)
y <- tr$TARGET

tr_te <- tr %>% 
  select(-TARGET) %>% 
  bind_rows(te) %>%
  select(-SK_ID_CURR) %>% 
  mutate_if(is.character, as.factor) %>% 
  mutate(na = apply(., 1, function(x) sum(is.na(x))),
         DAYS_EMPLOYED = ifelse(DAYS_EMPLOYED == 365243, NA, DAYS_EMPLOYED),
         DAYS_EMPLOYED_PERC = sqrt(DAYS_EMPLOYED / DAYS_BIRTH),
         INCOME_CREDIT_PERC = AMT_INCOME_TOTAL / AMT_CREDIT,
         INCOME_PER_PERSON = log1p(AMT_INCOME_TOTAL / CNT_FAM_MEMBERS),
         ANNUITY_INCOME_PERC = sqrt(AMT_ANNUITY / (1 + AMT_INCOME_TOTAL)),
         LOAN_INCOME_RATIO = AMT_CREDIT / AMT_INCOME_TOTAL,
         ANNUITY_LENGTH = AMT_CREDIT / AMT_ANNUITY,
         CHILDREN_RATIO = CNT_CHILDREN / CNT_FAM_MEMBERS, 
         CREDIT_TO_GOODS_RATIO = AMT_CREDIT / AMT_GOODS_PRICE,
         INC_PER_CHLD = AMT_INCOME_TOTAL / (1 + CNT_CHILDREN),
         SOURCES_PROD = EXT_SOURCE_1 * EXT_SOURCE_2 * EXT_SOURCE_3,
         CAR_TO_BIRTH_RATIO = OWN_CAR_AGE / DAYS_BIRTH,
         CAR_TO_EMPLOY_RATIO = OWN_CAR_AGE / DAYS_EMPLOYED,
         PHONE_TO_BIRTH_RATIO = DAYS_LAST_PHONE_CHANGE / DAYS_BIRTH,
         PHONE_TO_BIRTH_RATIO = DAYS_LAST_PHONE_CHANGE / DAYS_EMPLOYED) 

docs <- str_subset(names(tr), "FLAG_DOC")
live <- str_subset(names(tr), "(?!NFLAG_)(?!FLAG_DOC)(?!_FLAG_)FLAG_")
inc_by_org <- tr_te %>% 
  group_by(ORGANIZATION_TYPE) %>% 
  summarise(m = median(AMT_INCOME_TOTAL)) %$% 
  setNames(as.list(m), ORGANIZATION_TYPE)

nzv_cols <- nearZeroVar(tr_te)
tr_te <- tr_te[, -nzv_cols]

rm(tr, te, fn, sum_bureau, sum_cc_balance, 
   sum_payments, sum_pc_balance, sum_prev); gc()
```

```{r, include=FALSE}
tr <- read_csv("application_train.csv") 
te <- read_csv("application_test.csv")
```


```{r, include=FALSE}
tri <- 1:nrow(tr)
y <- tr$TARGET

tr_te2 <- tr %>% 
  select(-TARGET) %>% 
  bind_rows(te) %>%
  select(-SK_ID_CURR) %>% 
  mutate_if(is.character, funs(factor(.) %>% as.integer)) %>% 
  mutate(na = apply(., 1, function(x) sum(is.na(x))),
         DAYS_EMPLOYED = ifelse(DAYS_EMPLOYED == 365243, NA, DAYS_EMPLOYED),
         DAYS_EMPLOYED_PERC = sqrt(DAYS_EMPLOYED / DAYS_BIRTH),
         INCOME_CREDIT_PERC = AMT_INCOME_TOTAL / AMT_CREDIT,
         INCOME_PER_PERSON = log1p(AMT_INCOME_TOTAL / CNT_FAM_MEMBERS),
         ANNUITY_INCOME_PERC = sqrt(AMT_ANNUITY / (1 + AMT_INCOME_TOTAL)),
         LOAN_INCOME_RATIO = AMT_CREDIT / AMT_INCOME_TOTAL,
         ANNUITY_LENGTH = AMT_CREDIT / AMT_ANNUITY,
         CHILDREN_RATIO = CNT_CHILDREN / CNT_FAM_MEMBERS, 
         CREDIT_TO_GOODS_RATIO = AMT_CREDIT / AMT_GOODS_PRICE,
         INC_PER_CHLD = AMT_INCOME_TOTAL / (1 + CNT_CHILDREN),
         SOURCES_PROD = EXT_SOURCE_1 * EXT_SOURCE_2 * EXT_SOURCE_3,
         CAR_TO_BIRTH_RATIO = OWN_CAR_AGE / DAYS_BIRTH,
         CAR_TO_EMPLOY_RATIO = OWN_CAR_AGE / DAYS_EMPLOYED,
         PHONE_TO_BIRTH_RATIO = DAYS_LAST_PHONE_CHANGE / DAYS_BIRTH,
         PHONE_TO_BIRTH_RATIO = DAYS_LAST_PHONE_CHANGE / DAYS_EMPLOYED) 

docs <- str_subset(names(tr), "FLAG_DOC")
live <- str_subset(names(tr), "(?!NFLAG_)(?!FLAG_DOC)(?!_FLAG_)FLAG_")
inc_by_org <- tr_te %>% 
  group_by(ORGANIZATION_TYPE) %>% 
  summarise(m = median(AMT_INCOME_TOTAL)) %$% 
  setNames(as.list(m), ORGANIZATION_TYPE)

rm(tr, te, fn, sum_bureau, sum_cc_balance, 
   sum_payments, sum_pc_balance, sum_prev); gc()
```

```{r, include=FALSE}
tr_te2 %<>% 
  mutate(DOC_IND_KURT = apply(tr_te2[, docs], 1, moments::kurtosis),
         LIVE_IND_SUM = apply(tr_te2[, live], 1, sum),
         NEW_INC_BY_ORG = recode(tr_te2$ORGANIZATION_TYPE, !!!inc_by_org),
         NEW_EXT_SOURCES_MEAN = apply(tr_te2[, c("EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3")], 1, mean),
         NEW_SCORES_STD = apply(tr_te2[, c("EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3")], 1, sd))%>%
  mutate_all(funs(ifelse(is.nan(.), NA, .))) %>% 
  mutate_all(funs(ifelse(is.infinite(.), NA, .)))
```

```{r, include=FALSE}
tr_te2_PCA <- na.aggregate(tr_te2)
```

```{r, include=FALSE}
nzv_cols <- nearZeroVar(tr_te2_PCA)
tr_te2_PCA <- tr_te2_PCA[, -nzv_cols]
```

```{r, include=FALSE}
regexp <- "[[:digit:]]+"
pcaObject <- prcomp(tr_te2_PCA,  scale = TRUE, center = TRUE)
```

```{r}
set.seed(42)
tri2 <- caret::createDataPartition(y, p = 0.8, list = F) %>% c()

knn_data <- tr_te2_PCA[tri, ]
knntrain <-  knn_data[tri2, ]
knnval <-  knn_data[-tri2, ]
```

```{r, include=FALSE}
set.seed(123)
new.data1 <- knnExtract(xtr = as.matrix(knntrain), ytr = as.factor(y[tri2]), xte = as.matrix(knnval), k = 3)
new.data2 <- knnExtract(xtr = as.matrix(knntrain), ytr = as.factor(y[tri2]), xte = as.matrix(tr_te2_PCA[-tri, ]), k = 3)
```

```{r, include=FALSE}
df_corr = cor(na.omit(tr_te2_PCA))
hc = findCorrelation(df_corr, cutoff=0.7)
hc = sort(hc)
dt1_num3 = as.data.frame(tr_te2_PCA)[,-c(hc)]

rm_col_hc <- setdiff(colnames(tr_te2_PCA), colnames(dt1_num3))
```

```{r, include=FALSE}
tr_te <- data.frame(tr_te, tr_te2[, 135:139], pcaObject$x[,  1:10])

tr_te <- as.data.frame(tr_te)[, !(colnames(tr_te) %in% rm_col_hc)]

rm(tr_te2, tr_te2_PCA, pcaObject); gc(); gc()
```

```{r, include=FALSE}
set.seed(71)
dtest <- tr_te[-tri, ]
work <-tr_te[tri, ]

dtest <- data.frame(dtest, new.data2$new.te)
```

```{r}
work[which(work == -Inf, TRUE)] <- NA
work[which(work == -NaN, TRUE)] <- NA

dtrain <- data.frame(work[tri2, ], new.data1$new.tr)
dval <- data.frame(work[-tri2, ], new.data1$new.te)
```


```{r}
dtrain <-  catboost.load_pool(dtrain, label = y[tri2])
dval <-  catboost.load_pool(dval, label = y[-tri2])
```

```{r}
fit_params <- list(iterations = 1000,
                   thread_count = 7,
                   eval_metric = 'AUC',
                   loss_function = 'Logloss',
                   border_count = 64,
                   depth = 7,
                   rsm = 0.7,
                   subsample = 0.66,
                   learning_rate = 0.05,
                   l2_leaf_reg = 0.5,
                   one_hot_max_size = 5,
                   od_type = 'Iter',
                   od_wait = 30,
                   random_seed = 71,
                   bootstrap_type= 'Bernoulli',
                   class_weights = c(0.2, 1)
                   )
```

```{r}
set.seed(71)
model <- catboost.train(dtrain, dval, fit_params)
```

```{r}
test <-  catboost.load_pool(dtest)
```

```{r, include=FALSE}
read_csv("sample_submission.csv") %>%  
  mutate(SK_ID_CURR = as.integer(SK_ID_CURR),
         TARGET = catboost.predict(model, test, prediction_type = 'Probability')) %>%
  write_csv("cat_0.764.csv")
```





