---
title: "Untitled"
author: "Eguchi"
date: "2018/7/3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

## package loading
```{r setup, include=FALSE}
library(tidyverse); library(lightgbm); library(magrittr); library(moments);  library(zoo);
library(sessioninfo); library(IROmiss); library(caret); library(irlba); library(DT);
library(catboost); library(data.table); library(stringr); library(fastknn); library(tictoc);
library(viridis); library(skimr); library(GGally); library(plotly); library(xgboost); library(missRanger)
```


## sum_bbalance
```{r, echo=FALSE, include=FALSE}
bbalance <- read_csv("bureau_balance.csv") 
```

```{r}
fn <- funs(median, sd, skewness, min, max, sum, n_distinct, moments::kurtosis, (na.rm = TRUE))
```

```{r}
sum_bbalance <- bbalance %>%
  mutate_if(is.character, funs(factor(.) %>% as.integer)) %>% 
  group_by(SK_ID_BUREAU) %>% 
  summarise_all(fn) 
rm(bbalance); gc(); gc()
```

## sum_bureau
```{r, include=FALSE}
bureau <- read_csv("bureau.csv")
```

```{r, include=FALSE}
sum_bureau <- bureau %>% 
  left_join(sum_bbalance, by = "SK_ID_BUREAU") %>% 
  select(-SK_ID_BUREAU) %>% 
  mutate_if(is.character, funs(factor(.) %>% as.integer)) %>% 
  group_by(SK_ID_CURR) %>% 
  summarise_all(fn)
rm(bureau, sum_bbalance); gc(); gc()
```

## sum_cc_balance
```{r, include=FALSE}
cc_balance <- read_csv("credit_card_balance.csv")
```

```{r, include=FALSE}
sum_cc_balance <- cc_balance %>% 
  select(-SK_ID_PREV) %>% 
  mutate_if(is.character, funs(factor(.) %>% as.integer)) %>% 
  group_by(SK_ID_CURR) %>% 
  summarise_all(fn)
rm(cc_balance); gc(); gc()
```

## payments
```{r, include=FALSE}
payments <- read_csv("installments_payments.csv") 
```

```{r, include=FALSE}
sum_payments <- payments %>% 
  select(-SK_ID_PREV) %>% 
  mutate(PAYMENT_PERC = AMT_PAYMENT / AMT_INSTALMENT,
         PAYMENT_DIFF = AMT_INSTALMENT - AMT_PAYMENT,
         DPD = DAYS_ENTRY_PAYMENT - DAYS_INSTALMENT,
         DBD = DAYS_INSTALMENT - DAYS_ENTRY_PAYMENT,
         DPD = ifelse(DPD > 0, DPD, 0),
         DBD = ifelse(DBD > 0, DBD, 0)) %>% 
  group_by(SK_ID_CURR) %>% 
  summarise_all(fn) 
rm(payments); gc(); gc()
```

## payments
```{r, include=FALSE}
pc_balance <- read_csv("POS_CASH_balance.csv")
```

```{r, include=FALSE}
sum_pc_balance <- pc_balance %>% 
  select(-SK_ID_PREV) %>% 
  mutate_if(is.character, funs(factor(.) %>% as.integer)) %>% 
  group_by(SK_ID_CURR) %>% 
  summarise_all(fn)
rm(pc_balance); gc(); gc()
```

## prev
```{r, include=FALSE}
prev <- read_csv("previous_application.csv")
```

```{r, include=FALSE}
sum_prev <- prev %>%
  select(-SK_ID_PREV) %>% 
  mutate_if(is.character, funs(factor(.) %>% as.integer)) %>% 
  mutate(DAYS_FIRST_DRAWING = ifelse(DAYS_FIRST_DRAWING == 365243, NA, DAYS_FIRST_DRAWING),
         DAYS_FIRST_DUE = ifelse(DAYS_FIRST_DUE == 365243, NA, DAYS_FIRST_DUE),
         DAYS_LAST_DUE_1ST_VERSION = ifelse(DAYS_LAST_DUE_1ST_VERSION == 365243, NA, DAYS_LAST_DUE_1ST_VERSION),
         DAYS_LAST_DUE = ifelse(DAYS_LAST_DUE == 365243, NA, DAYS_LAST_DUE),
         DAYS_TERMINATION = ifelse(DAYS_TERMINATION == 365243, NA, DAYS_TERMINATION),
         APP_CREDIT_PERC = AMT_APPLICATION / AMT_CREDIT) %>% 
  group_by(SK_ID_CURR) %>% 
  summarise_all(fn) 
rm(prev); gc(); gc()
```

## train_test
```{r, include=FALSE}
tr <- read_csv("application_train.csv") 
te <- read_csv("application_test.csv")
```


```{r, include=FALSE}
tri <- 1:nrow(tr)
y <- tr$TARGET

tr_te <- tr %>% 
  select(-TARGET) %>% 
  bind_rows(te) %>%
  left_join(sum_bureau, by = "SK_ID_CURR") %>% 
  left_join(sum_cc_balance, by = "SK_ID_CURR") %>% 
  left_join(sum_payments, by = "SK_ID_CURR") %>% 
  left_join(sum_pc_balance, by = "SK_ID_CURR") %>% 
  left_join(sum_prev, by = "SK_ID_CURR") %>% 
  select(-SK_ID_CURR) %>% 
  mutate_if(is.character, funs(factor(.) %>% as.integer)) %>% 
  mutate(na = apply(., 1, function(x) sum(is.na(x))),
         DAYS_EMPLOYED = ifelse(DAYS_EMPLOYED == 365243, NA, DAYS_EMPLOYED),
         DAYS_EMPLOYED_PERC = sqrt(DAYS_EMPLOYED / DAYS_BIRTH),
         INCOME_CREDIT_PERC = AMT_INCOME_TOTAL / AMT_CREDIT,
         INCOME_PER_PERSON = log1p(AMT_INCOME_TOTAL / CNT_FAM_MEMBERS),
         ANNUITY_INCOME_PERC = sqrt(AMT_ANNUITY / (1 + AMT_INCOME_TOTAL)),
         NEW_CREDIT_TO_INCOME_RATIO = AMT_CREDIT / AMT_INCOME_TOTAL,
         LOAN_INCOME_RATIO = AMT_CREDIT / AMT_INCOME_TOTAL,
         ANNUITY_LENGTH = AMT_CREDIT / AMT_ANNUITY,
         CHILDREN_RATIO = CNT_CHILDREN / CNT_FAM_MEMBERS, 
         CREDIT_TO_GOODS_RATIO = AMT_CREDIT / AMT_GOODS_PRICE,
         INC_PER_CHLD = AMT_INCOME_TOTAL / (1 + CNT_CHILDREN),
         SOURCES_PROD = EXT_SOURCE_1 * EXT_SOURCE_2 * EXT_SOURCE_3,
         CAR_TO_BIRTH_RATIO = OWN_CAR_AGE / DAYS_BIRTH,
         CAR_TO_EMPLOY_RATIO = OWN_CAR_AGE / DAYS_EMPLOYED,
         PHONE_TO_BIRTH_RATIO = DAYS_LAST_PHONE_CHANGE / DAYS_BIRTH,
         PHONE_TO_BIRTH_RATIO = DAYS_LAST_PHONE_CHANGE / DAYS_EMPLOYED) 

docs <- str_subset(names(tr), "FLAG_DOC")
live <- str_subset(names(tr), "(?!NFLAG_)(?!FLAG_DOC)(?!_FLAG_)FLAG_")
inc_by_org <- tr_te %>% 
  group_by(ORGANIZATION_TYPE) %>% 
  summarise(m = median(AMT_INCOME_TOTAL)) %$% 
  setNames(as.list(m), ORGANIZATION_TYPE)

rm(tr, te, fn, sum_bureau, sum_cc_balance, 
   sum_payments, sum_pc_balance, sum_prev); gc()
```

```{r, include=FALSE}
tr_te %<>% 
  mutate(DOC_IND_KURT = apply(tr_te[, docs], 1, moments::kurtosis),
         LIVE_IND_SUM = apply(tr_te[, live], 1, sum),
         NEW_INC_BY_ORG = recode(tr_te$ORGANIZATION_TYPE, !!!inc_by_org),
         NEW_EXT_SOURCES_MEAN = apply(tr_te[, c("EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3")], 1, mean),
         NEW_SCORES_STD = apply(tr_te[, c("EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3")], 1, sd))%>%
  mutate_all(funs(ifelse(is.nan(.), NA, .))) %>% 
  mutate_all(funs(ifelse(is.infinite(.), NA, .)))
```

## remove nearZero
```{r, include=FALSE}
nzv_cols <- nearZeroVar(tr_te)
tr_te <- tr_te[, -nzv_cols]

gc(); gc()
```

## remove corr
```{r, include=FALSE}
tr_te_agg <- na.aggregate(tr_te)
df_corr = cor(na.omit(tr_te_agg))
hc = findCorrelation(df_corr, cutoff=0.7)
hc = sort(hc)
dt1_num3 = as.data.frame(tr_te_agg)[,-c(hc)]

rm_col_hc <- setdiff(colnames(tr_te_agg), colnames(dt1_num3))
tr_te <- as.data.frame(tr_te)[, !(colnames(tr_te) %in% rm_col_hc)]
rm(tr_te_agg); gc(); gc()
```

## knn feature
```{r}
set.seed(42)
tri2 <- caret::createDataPartition(y, p = 0.8, list = F) %>% c()

knn_data <- tr_te[tri, ]
knntrain <-  knn_data[tri2, ]
knnval <-  knn_data[-tri2, ]

knntrain <- na.aggregate(knntrain)
knnval <- na.aggregate(knnval)
rm(knn_data); gc(); gc()

set.seed(71)
new.data1 <- knnExtract(xtr = as.matrix(knntrain), ytr = as.factor(y[tri2]), xte = as.matrix(knnval), k = 5)
knntest <- na.aggregate(tr_te[-tri, ])
new.data2 <- knnExtract(xtr = as.matrix(knntrain), ytr = as.factor(y[tri2]), xte = as.matrix(knntest), k = 5)
rm(knntrain, knnval); gc(); gc()
```

# OHE feature
```{r, include=FALSE}
tr <- read_csv("application_train.csv") 
te <- read_csv("application_test.csv")

docs <- str_subset(names(tr), "FLAG_DOC")
live <- str_subset(names(tr), "(?!NFLAG_)(?!FLAG_DOC)(?!_FLAG_)FLAG_")

tri <- 1:nrow(tr)
y <- tr$TARGET

tr_te3 <- tr %>% 
  select(-TARGET) %>% 
  bind_rows(te) %>%
  select(-SK_ID_CURR) %>% 
  mutate_if(is.character, as.factor)

fac_trte <- data.frame(tr_te3[, docs], tr_te3[, live]) %>%
  mutate_if(is.integer, as.factor)
rm(tr, te, tr_te3); gc(); gc()

set.seed(42)
tri2 <- caret::createDataPartition(y, p = 0.8, list = F) %>% c()

fac_data <- fac_trte[tri, ]
fac_train <-  fac_data[tri2, ]
fac_val <-  fac_data[-tri2, ]
fac_test <- fac_trte[-tri, ]

dummies1 = dummyVars(~., data = fac_train)
dummies2 = dummyVars(~., data = fac_val)
dummies3 = dummyVars(~., data = fac_test)

fac_train <- as.data.frame(predict(dummies1, newdata = fac_train))
fac_val <- as.data.frame(predict(dummies2, newdata = fac_val))
fac_test <- as.data.frame(predict(dummies3, newdata = fac_test))
```

## train test val
```{r, include=FALSE}
set.seed(71)
dtest <- tr_te[-tri, ]
work <-tr_te[tri, ]

dtest <- data.frame(dtest, new.data2$new.te, fac_test)

work[which(work == -Inf, TRUE)] <- NA
work[which(work == -NaN, TRUE)] <- NA

dtrain <- data.frame(work[tri2, ], new.data1$new.tr, fac_train)
dval <- data.frame(work[-tri2, ], new.data1$new.te, fac_val)
rm(new.data1, new.data2, fac_train, fac_val, fac_test); gc(); gc()
```

## Set categorical features
```{r}
categorical_features = c('NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE',
                          'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE',
                          'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE', 'WALLSMATERIAL_MODE')

lgb.train = lgb.Dataset(data.matrix(dtrain), label = y[tri2], categorical_feature = categorical_features)
lgb.valid = lgb.Dataset(data.matrix(dval), label = y[-tri2], categorical_feature = categorical_features)

rm(dtrain, dval, fac_dtrain, fac_dval, fac_dtest, tr, te, tr_te); gc(); gc()
```

## LGBM param
```{r}
set.seed(71)
params = list(objective = "binary", 
              metric = "auc", 
              learning_rate= 0.02, 
              num_leaves= 256,
              max_bin= 255, # RAM dependent as per LightGBM documentation
              subsample= 0.85,
              subsample_freq= 1,
              colsample_bytree= 0.9,
              reg_alpha=0.04,
              reg_lambda=0.075,
              min_split_gain=0.02,
              min_child_weight= 40,
              scale_pos_weight=11) # calculated for this dataset
```  

## Train LGBM
```{r}
set.seed(71)
lgb.model <- lgb.train(
      params = params
      , data = lgb.train
      , valids = list(val = lgb.valid)
      , nrounds = 10000
      , early_stopping_rounds = 200
      , eval_freq = 50
    )
```

## Varimp
```{r}
lgb.importance(lgb.model, percentage = TRUE) %>% head(20) %>% kable()
tree_imp <- lgb.importance(lgb.model, percentage = TRUE) %>% head(20)
lgb.plot.importance(tree_imp, measure = "Gain")
```

## submit
```{r, include=FALSE}
sample_submission <- read_csv("sample_submission.csv")
sample_submission %>%
    mutate(SK_ID_CURR = as.integer(SK_ID_CURR),
    TARGET = predict(lgb.model, data = data.matrix(dtest), n = lgb.model$best_iter)) %>%
    write_csv("lightgbm_782.csv")
```





